// Load writing entries from publishedEntries — always up-to-date with new essays.
// Avoids stale DB seed data that didn't include new entries.
import { publishedEntries } from "$lib/writing-data";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

export async function load() {
  const totalWords = publishedEntries.reduce((sum, e) => sum + (e.words || 0), 0);
  const readingTimeMinutes = Math.max(1, Math.round(totalWords / 200));

  // Date range: oldest → newest essay createdAt
  let firstDate = null;
  let latestDate = null;
  for (const entry of publishedEntries) {
    const d = entry.createdAt;
    if (d instanceof Date && !isNaN(+d)) {
      if (!firstDate || d < firstDate) firstDate = d;
      if (!latestDate || d > latestDate) latestDate = d;
    }
  }

  // Read recently-edited essays data (generated by scripts/check-edited-essays.sh at build time)
  /** @type {Record<string, string>} slug → relative label e.g. "edited 2d ago" */
  const editedLabels = {};
  const editedPath = join(process.cwd(), "src/lib/generated/edited-essays.json");
  if (existsSync(editedPath)) {
    try {
      /** @type {Record<string, number>} */
      const editedTimestamps = JSON.parse(readFileSync(editedPath, "utf-8"));
      const now = Date.now();
      const msPerSec = 1000;
      for (const [slug, ts] of Object.entries(editedTimestamps)) {
        const diffMs = now - ts * msPerSec;
        const mins = Math.floor(diffMs / 60000);
        const hours = Math.floor(diffMs / 3600000);
        const days = Math.floor(diffMs / 86400000);
        let label;
        if (mins < 60) label = `edited ${mins}m ago`;
        else if (hours < 24) label = `edited ${hours}h ago`;
        else label = `edited ${days}d ago`;
        editedLabels[slug] = label;
      }
    } catch {
      // silently ignore — missing or malformed file
    }
  }

  // Count essays and words this calendar month
  const now = new Date();
  const thisMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  const thisMonthEntries = publishedEntries.filter(e => e.date.startsWith(thisMonth));
  const thisMonthCount = thisMonthEntries.length;
  const thisMonthWords = thisMonthEntries.reduce((sum, e) => sum + (e.words || 0), 0);

  return { entries: publishedEntries, totalWords, thisMonthWords, thisMonthCount, readingTimeMinutes, firstDate, latestDate, editedLabels };
}
